version: "3.9"

services:
  profissionais-db:
    image: "postgres:latest"
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user123
      POSTGRES_DB: gerenciador_profissionais
    ports:
      - "5432:5432"
    volumes:
      - ./01-gerenciador-profissionais.sql:/tmp/01-gerenciador-profissionais.sql